### ISSUE TITLE
Year hardcoded

### ISSUE THREAD

**Issue by Sun42** [JulienAldon/EEPlanner#1]
https://github.com/JulienAldon/EpitechEventPlanner/blob/6df291aeb8ca49f067d5384ba2a167dbf1128756/src/intranet.py#L91

Worth it to set it as a third param ? 
Default value could be : 
 if currentMonth between Sept-Dec:
   year = currentYear 
 else #Jan - Aug 
 year = currentYear-1

**Comment by JulienAldon** [comment]
For now it isn't a problem but could easily become one. I'll fix this.

**Comment by JulienAldon** [comment]
fixed in commit [80de092](https://github.com/JulienAldon/EpitechEventPlanner/commit/80de092af13428e645f887b2e63d86b9b5b277f6)
It is now possible to set the promotion year in the interface
It is set by default to the current year -1. (A later fix will set it to the current academic year)
